
import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './themeColor/ButtonTheme'
import AuthWrapper from './hoc/authWrapper'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>{<AuthWrapper >{children}</AuthWrapper>}</body>
      </ThemeProvider>
    </html>
  )
}
